version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local

  nginx:
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl

