# 1. 빌드 환경: JDK가 포함된 이미지 사용
FROM openjdk:21-jdk-slim as builder

# 작업 디렉토리 설정
WORKDIR /app

# 전체 소스코드 복사
COPY . .

# gradlew 실행 권한 부여
RUN chmod +x ./gradlew

# 테스트를 제외하고 애플리케이션 빌드
RUN ./gradlew build -x test

# 2. 실행 환경: JRE만 포함된 가벼운 이미지 사용
FROM eclipse-temurin:21-jdk

WORKDIR /app

# 빌드 환경(builder)에서 빌드된 jar 파일만 복사
COPY --from=builder /app/build/libs/*.jar app.jar

# 애플리케이션 포트 노출
EXPOSE 8080

# 애플리케이션 실행
ENTRYPOINT ["java", "-jar", "app.jar"]
