spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_INTERNAL_PORT/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      initialization-fail-timeout: 0  # DB 준비 안 됐으면 재시도
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_INTERNAL_PORT}
      password: