spring:
  datasource:
    url: jdbc:mysql://${LOCAL_HOST}:${MYSQL_EXTERNAL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${LOCAL_HOST}
      port: ${REDIS_EXTERNAL_PORT}
      password:

custom:
  site:
    frontUrl: http://${LOCAL_HOST}:${FRONTEND_EXTERNAL_PORT}
    backUrl: http://${LOCAL_HOST}:${SPRING_INTERNAL_PORT}