spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_INTERNAL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_INTERNAL_PORT}
      password:

custom:
  site:
    frontUrl: http://${LOCAL_HOST}:${FRONTEND_INTERNAL_PORT}