name: YETDA 백엔드 자동 배포

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 서버에 필요한 디렉토리 생성
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            mkdir -p /home/${{ secrets.DEPLOY_USER }}/yetda/backend/build/libs

      - name: 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: JDK 설정 (Java 21)
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew
        working-directory: ./backend

      - name: Gradle로 빌드 (테스트 제외)
        run: ./gradlew build -x test
        working-directory: ./backend

      - name: jar 복사
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          source: backend/build/libs/*.jar
          target: /home/${{ secrets.DEPLOY_USER }}/yetda

      - name: Dockerfile 복사
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          source: backend/Dockerfile
          target: /home/${{ secrets.DEPLOY_USER }}/yetda

      - name: docker compose 복사
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          source: docker-compose.yml
          target: /home/${{ secrets.DEPLOY_USER }}/yetda

      - name: 서버에서 docker compose 재실행
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT || 22 }}
          script: |
            cd /home/${{ secrets.DEPLOY_USER }}/yetda
            docker-compose up -d --build